traefik:
  image:
    tag: "v3.0"
  
  deployment:
    replicas: 2
  
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /ping
  
  ports:
    web:
      port: 8000
      exposedPort: 80
    websecure:
      port: 8443
      exposedPort: 443
  
  ingressClass:
    enabled: true
    isDefaultClass: true
  
  logs:
    general:
      level: INFO